import {beforeEach,describe,it,expect,vi} from 'vitest';
import {Platform,BOARD} from '../src/platform/platform';
const record={schemaVersion:1 as const,trackVersion:'t',physicsVersion:'p',time:50000,splits:[1,2,3,4,5,6,50000],frames:[]};
beforeEach(()=>{const values=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>values.set(k,v)});vi.stubGlobal('window',{GameSDK:{isPlatformSDKError:(e:any)=>typeof e?.code==='string'}});});
describe('platform result and storage boundaries',()=>{
 it('an old settlement response cannot replace the new race status',async()=>{let resolve!:(value:unknown)=>void;const submit=vi.fn(()=>new Promise(r=>{resolve=r})),status=vi.fn(),p=new Platform('t','p',status);p.sdk={context:{gameId:1,user:{id:'a'},sessionId:'session'},on:()=>()=>{},leaderboard:{submit,getTop:vi.fn(),getMyValue:vi.fn()}};const pending=p.submit('old-race',50000);p.settlement++;resolve({targets:[]});await pending;expect(status).not.toHaveBeenCalled();});
 it('NO_CHANGE is accepted and does not submit twice',async()=>{const status=vi.fn(),submit=vi.fn().mockResolvedValue({targets:[{effect:'NO_CHANGE',projection:{status:'READY'}}]});const p=new Platform('t','p',status);p.sdk={context:{gameId:1,user:{id:'a'}},on:()=>()=>{},leaderboard:{submit,getTop:vi.fn(),getMyValue:vi.fn()}};await p.submit('stable-id',50000);expect(submit).toHaveBeenCalledTimes(1);expect(submit).toHaveBeenCalledWith({boardCode:BOARD,submissionId:'stable-id',payload:{type:'numeric',value:50000}});expect(status).toHaveBeenCalledWith('成绩已提交');});
 it('denied permission is terminal for this result; new results still submit',async()=>{const submit=vi.fn().mockRejectedValueOnce({code:'PERMISSION_DENIED'}).mockResolvedValue({targets:[]});const p=new Platform('t','p',()=>{});p.sdk={context:{gameId:1,user:{id:'a'}},on:()=>()=>{},leaderboard:{submit,getTop:vi.fn(),getMyValue:vi.fn()}};await p.submit('first',50000);await p.submit('second',55000);expect(submit).toHaveBeenCalledTimes(2);expect(submit.mock.calls[1][0].submissionId).toBe('second');});
 it('a failed cloud read never overwrites a remote record',async()=>{const set=vi.fn(),p=new Platform('t','p',()=>{});p.sdk={context:{gameId:1,user:{id:'a'}},on:()=>()=>{},storage:{get:vi.fn().mockRejectedValue({code:'STORAGE_NETWORK_ERROR'}),set}};await p.load();p.best=record;await p.save();expect(set).not.toHaveBeenCalled();expect(localStorage.getItem(p.key())).toContain('50000');});
 it('CAS preserves a faster cloud best with its matching replay',async()=>{const set=vi.fn().mockResolvedValue({ok:true,version:3});const p=new Platform('t','p',()=>{});p.best={...record,time:60000,splits:[1,2,3,4,5,6,60000]};p.ready=true;p.sdk={context:{gameId:1,user:{id:'a'}},on:()=>()=>{},storage:{get:vi.fn().mockResolvedValue({value:{best:record},version:2}),set}};await p.save();expect(set.mock.calls[0][0].ifVersion).toBe(2);expect(set.mock.calls[0][0].value.best.time).toBe(50000);expect(p.best?.time).toBe(50000);});
 it('a slower-than-lifetime-best race still gets submitted for a new window',async()=>{const submit=vi.fn().mockResolvedValue({targets:[]}),p=new Platform('t','p',()=>{});p.best=record;p.sdk={context:{gameId:1,user:{id:'a'}},on:()=>()=>{},leaderboard:{submit,getTop:vi.fn(),getMyValue:vi.fn()}};await p.submit('new-period',70000);expect(submit.mock.calls[0][0].payload.value).toBe(70000);});
});
