import {spawn} from 'node:child_process';
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import path from 'node:path';
const cli=path.join(process.env.APPDATA,'npm/node_modules/tripo-cli/dist/cli.js');
const common='Original stylized low polygon sky racing world, clean ivory and dark slate surfaces with cyan crystal and small orange accents, strong simple silhouette, isolated single game prop, no text, no logos. ';
const jobs=[];
for(const [name,prompt,seed] of [['car-b','An original futuristic open wheel single seat sprint race car, angular arrow shaped nose, cyan white panels, four black wheels, rear wing, simple faceted toy-like design',102],['car-c','An original compact rally prototype racing coupe, rounded low canopy, orange white and cyan geometric panels, four black wheels, bold stylized silhouette',103]])jobs.push({name,model:'tripo-p2',prompt,seed,params:['face_limit=10000','texture_quality=detailed']});
for(const [name,prompt] of [['crystal-island','A floating rock island crowned by a cluster of enormous translucent cyan crystals, pale stone platform'],['energy-core','A futuristic vertical circular energy portal monument, cyan luminous core suspended in a chunky ivory mechanical frame'],['finish-tower','A tall futuristic finish line observation tower, orange viewing pod and white angular supports']])for(let n=1;n<=2;n++)jobs.push({name:`${name}-${n}`,model:'tripo-v3.1',prompt:common+prompt,seed:200+jobs.length,params:['smart_low_poly=true','face_limit=6500','texture_quality=detailed']});
for(const [name,prompt] of [['floating-rock','A broad floating basalt rock with a flat grassy top and sharp tapered underside'],['crystal-cluster','A cluster of five angular cyan crystals on a small dark stone base'],['watchtower','A small futuristic track marshal watchtower on a single pylon'],['energy-crate','A compact cube energy supply crate with glowing cyan slits'],['flag','A rigid triangular cyan racing flag on a freestanding white pedestal'],['antenna','A small stylized satellite antenna relay mast'],['beacon','An orange futuristic hazard beacon bollard'],['arch','A decorative wide ivory open racing arch with cyan light strips']])for(let n=1;n<=2;n++)jobs.push({name:`${name}-${n}`,model:'tripo-p1',prompt:common+prompt,seed:300+jobs.length,params:['face_limit=3000']});
mkdirSync('assets/source/receipts',{recursive:true});writeFileSync('assets/source/manifest.json',JSON.stringify(jobs,null,2));
function run(args){return new Promise(resolve=>{const p=spawn(process.execPath,[cli,...args],{env:{...process.env,HTTPS_PROXY:'http://127.0.0.1:10808',HTTP_PROXY:'http://127.0.0.1:10808',NODE_USE_ENV_PROXY:'1'},windowsHide:true});let out='',err='';p.stdout.on('data',x=>out+=x);p.stderr.on('data',x=>err+=x);p.on('exit',code=>resolve({code,out,err}));});}
const args=j=>['make',j.prompt,'--model',j.model,...j.params.flatMap(x=>['-p',x]),'--seed',String(j.seed),'--name',j.name,'-o','assets/source','--json'];
if(process.argv.includes('--plan')){for(const j of jobs){const result=await run([...args(j),'--dry-run']);writeFileSync(`assets/source/receipts/${j.name}.plan.json`,result.out);if(result.code)throw Error(result.err);console.log(`${j.name}: valid`);}process.exit(0);}
const queue=[...jobs];await Promise.all(Array.from({length:4},async()=>{while(queue.length){const job=queue.shift();const dest=`assets/source/receipts/${job.name}.json`;if(existsSync(dest)){try{if(JSON.parse(readFileSync(dest)).status==='success')continue;}catch{}}
 const plan=JSON.parse(readFileSync(`assets/source/receipts/${job.name}.plan.json`));if(!plan.valid)throw Error('Missing validated plan');const result=await run([...args(job),'--yes']);writeFileSync(dest,result.out);writeFileSync(`assets/source/receipts/${job.name}.log`,result.err);console.log(`${job.name}: ${result.code===0?'completed':'FAILED'}`);
}}));
