import RAPIER from '@dimforge/rapier3d-compat';
import {Vector3} from 'three';
import {Scene} from './scene/scene';
import {Vehicle} from './game/vehicle';
import {readControl} from './game/input';
import {Race,FixedClock,formatTime} from './game/race';
import {packFrame,playback,type Frame,type RecordData} from './game/replay';
import {vec,type Track} from './game/track';
import {Platform} from './platform/platform';
import {Sound} from './game/audio';
import './style.css';
import '@fontsource/barlow-condensed/latin-600.css';
import '@fontsource/barlow-condensed/latin-700.css';
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML='<div class="loading"><span>SKYLINE / SPRINT</span><h1>云端极速</h1><p>加载中…</p></div>';
async function boot(){
 await RAPIER.init();const response=await fetch('./assets/track.json');if(!response.ok)throw Error('赛道资源加载失败');const track:Track=await response.json();
 let vehicle=new Vehicle(track);const scene=new Scene(track,document.querySelector<HTMLCanvasElement>('#game')!),race=new Race(track.gates),clock=new FixedClock(),sound=new Sound();
 let mode:'menu'|'race'|'result'='menu',modal='',frames:Frame[]=[],last=performance.now(),nearest=0,lastCP=0,toast='正在连接星匣…',split='',boardGeneration=0,identityAtStart=0,lastGround=0,lastSpeed=0;const frameTimes:number[]=[];const diagnostics=new URLSearchParams(location.search).has('diagnostics');
 const platform=new Platform(track.trackVersion,track.physicsVersion,s=>{toast=s;const node=document.querySelector('#status');if(node)node.textContent=s;});
 const keys=new Set<string>(),touch=new Set<string>();const $=(id:string)=>document.getElementById(id)!;
 const escape=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 function renderUI(){
  if(mode==='menu')app.innerHTML=`<section class="screen"><div class="brand"><span class="brand-icon">///</span> SKYLINE SPRINT</div><div class="hero"><div class="eyebrow">云端折返 · 1.13 KM</div><h1>云端极速</h1><p class="desc">追逐你的最快一圈。</p><div class="actions"><button class="primary" id="start">开始 ↗</button><button class="secondary" id="leaderboard">排行</button><button class="secondary" id="settings">设置</button></div></div><aside class="track-card"><h3>云端折返</h3><canvas class="map" id="minimap" width="360" height="300"></canvas><div class="line"></div><div class="medals"><span><b>01:05</b>金</span><span><b>01:20</b>银</span><span><b>01:40</b>铜</span></div></aside><footer class="bottom"><span>WASD / 方向键 · R 重开 · C 复位</span></footer></section>`;
  else app.innerHTML=`<section class="hud"><div class="hud-top"><div class="pill"><div class="caption">用时</div><div class="time" id="time">00:00.000</div><div class="best" id="best">最佳 ${platform.best?formatTime(platform.best.time):'--:--.---'}</div><div class="split" id="split"></div><div class="practice" id="practice"></div></div><div><div class="actions"><button class="pill" id="restart">↻ 重开</button><button class="pill" id="settings">Ⅱ 设置</button></div><canvas class="map" id="minimap" width="360" height="300"></canvas><div class="pill" id="checkpoint">CP 0 / 6</div></div></div><div class="speed"><b id="speed">0</b><small>KM / H</small></div><div class="controls-hint">方向键驾驶 · 转弯按 ↓ 漂移<br>R 重开 · C 复位</div><div class="touch"><button data-control="left">◀</button><button data-control="right">▶</button><button data-control="handbrake">手刹</button><button data-control="brake">↓ 漂</button><button data-control="throttle">↑</button></div></section>`;
  app.insertAdjacentHTML('beforeend',`<div class="status" id="status">${escape(toast)}</div><div id="overlay"></div>${diagnostics?'<pre id="diagnostics" style="position:absolute;right:20px;top:160px;background:#081b32cc;padding:10px;font-size:11px"></pre>':''}`);
  document.querySelector('#start')?.addEventListener('click',()=>{try{if(!localStorage.getItem('skyline:help-seen')){help();return;}}catch{}start();});document.querySelector('#restart')?.addEventListener('click',start);document.querySelector('#settings')?.addEventListener('click',settings);document.querySelector('#leaderboard')?.addEventListener('click',()=>void leaderboard('weekly'));
  document.querySelectorAll<HTMLButtonElement>('[data-control]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch.add(b.dataset.control!);sound.start();};const release=()=>touch.delete(b.dataset.control!);b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;});drawMap();
 }
 function show(content:string){keys.clear();touch.clear();$('overlay').innerHTML=`<div class="modal"><section class="panel">${content}</section></div>`;}
 function close(){modal='';boardGeneration++;$('overlay').innerHTML='';clock.reset();last=performance.now();}
 function help(){modal='help';show('<h2>操作</h2><p>W / ↑ 加速 · S / ↓ 刹车<br>A D / ← → 转向 · 转弯按 S / ↓ 漂移<br>Space 手刹 · R 重开 · C 复位</p><p>依次过门，再冲线。<br>复位、暂停或离开窗口后，本局不计排名。</p><button class="primary" id="go">出发 ↗</button>');$('go').onclick=()=>{try{localStorage.setItem('skyline:help-seen','1');}catch{}start();};}
 function start(){close();sound.start();platform.settlement++;vehicle.dispose();vehicle=new Vehicle(track);scene.trails.clear();race.start(crypto.randomUUID());identityAtStart=platform.generation;mode='race';frames=[packFrame(0,vehicle.position,vehicle.rotation)];nearest=0;lastCP=0;split='';clock.reset();renderUI();}
 function practiceReset(){if(mode!=='race')return;race.invalidate('已复位 · 练习局');let index=race.next-1;while(index>=0&&track.gates[index].u[1]<.5)index--;const g=index>=0?track.gates[index]:track.spawn;vehicle.reset(g);scene.trails.clear();race.next=index+1;race.splits=race.splits.slice(0,race.next);lastCP=race.next;clock.reset();}
 function settings(){if(mode==='race')race.invalidate('已暂停 · 练习局');modal='settings';const s=platform.settings;
  show(`<h2>设置</h2><div class="row"><span>配色</span><div class="colors">${['#38d9ec','#ff9169','#bba2ff'].map(c=>`<button class="swatch ${s.color===c?'selected':''}" style="background:${c}" data-color="${c}" aria-label="配色 ${c}"></button>`).join('')}</div></div><label class="row">音效<input id="sfx" type="range" min="0" max="1" step=".05" value="${s.sfx}"></label><label class="row">音乐<input id="music" type="range" min="0" max="1" step=".05" value="${s.music}"></label><div class="row"><span>Sky Flight</span><button class="secondary" id="next-track">下一首 ♫</button></div><label class="row">低晃动<input id="lowMotion" type="checkbox" ${s.lowMotion?'checked':''}></label><label class="row">自动加速<input id="autoThrottle" type="checkbox" ${s.autoThrottle?'checked':''}></label><label class="row">显示幽灵<input id="ghost" type="checkbox" ${s.ghost?'checked':''}></label><label class="row">画质<select id="quality"><option value="high">标准</option><option value="low" ${s.quality==='low'?'selected':''}>流畅</option></select></label><div class="actions"><button class="primary" id="save">完成</button><button class="secondary" id="home">主页</button></div>`);
  document.querySelectorAll<HTMLButtonElement>('[data-color]').forEach(b=>b.onclick=()=>{s.color=b.dataset.color!;document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');});
  $('next-track').onclick=()=>{sound.start();sound.nextTrack();};
  $('save').onclick=()=>{s.sfx=Number(($('sfx') as HTMLInputElement).value);s.music=Number(($('music') as HTMLInputElement).value);for(const key of ['lowMotion','autoThrottle','ghost'] as const)s[key]=($ (key) as HTMLInputElement).checked;s.quality=($('quality') as HTMLSelectElement).value;applySettings();void platform.save();close();};$('home').onclick=()=>{close();mode='menu';race.running=false;vehicle.reset(track.spawn);renderUI();};
 }
 function applySettings(){const s=platform.settings;scene.setColor(s.color);scene.lowQuality=s.quality==='low';sound.sfx=s.sfx;sound.music=s.music;scene.renderer.setPixelRatio(s.quality==='low'?1:Math.min(devicePixelRatio,1.6));scene.resize();}
 async function leaderboard(view:string){modal='board';const generation=++boardGeneration;show(`<h2>排行榜</h2><div class="tabs">${[['daily','本日'],['weekly','本周'],['fourweekly','28 天周期']].map(([code,label])=>`<button data-view="${code}" class="${code===view?'active':''}">${label}</button>`).join('')}</div><div id="board-data">加载中…</div><div class="actions" style="margin-top:20px"><button class="secondary" id="back">返回</button></div>`);$('back').onclick=close;document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>void leaderboard(b.dataset.view!));
  try{const [top,mine]=await platform.board(view);if(generation!==boardGeneration)return;let info=top.projection.status==='EMPTY'?'暂无成绩':top.projection.status==='DELAYED'?'榜单更新中':'';let my='本期暂无成绩';if(mine.valueState==='DETAIL_EXPIRED')my='成绩已过期';if(mine.valueState==='AVAILABLE')my=`我的成绩 ${formatTime(mine.member.value)} · ${mine.projection.status==='PENDING'?'排名计算中':mine.projection.value.outsideTopK?'未进入展示范围':`第 ${mine.projection.value.rank} 名`}`;
   $('board-data').innerHTML=`<p>${escape(my)}</p><p>${info}</p><table><thead><tr><th>名次</th><th>车手</th><th>用时</th></tr></thead><tbody>${top.projection.status==='READY'?top.items.map((i:any)=>`<tr><td>${i.rank}</td><td>${escape(i.player.displayName??'车手')}</td><td>${formatTime(i.value)}</td></tr>`).join(''):''}</tbody></table>`;
   if(top.projection.status==='DELAYED')setTimeout(()=>{if(generation===boardGeneration)void leaderboard(view)},Math.max(1500,top.projection.retryAfter??3000));
  }catch(e){if(generation===boardGeneration)$('board-data').textContent=e instanceof Error?e.message:platform.error(e);}
 }
 function finish(){if((frames.at(-1)?.[0]??-1)<race.result)frames.push(packFrame(race.result,vehicle.position,vehicle.rotation));mode='result';sound.play('finish');const previous=platform.best;const improved=race.valid&&(!previous||race.result<previous.time);if(improved){const record:RecordData={schemaVersion:1,trackVersion:track.trackVersion,physicsVersion:track.physicsVersion,time:race.result,splits:[...race.splits],frames};platform.best=record;void platform.save();}if(race.valid)void platform.submit(race.id,race.result);
  modal='result';show(`<div class="eyebrow">${improved?'NEW PERSONAL BEST':'FINISH / SKYLINE'}</div><h2>${race.valid?improved?'新纪录':'完赛':'练习完赛'}</h2><div class="result-time">${formatTime(race.result)}</div><p>${race.reason?escape(race.reason):previous?`对比最佳 ${((race.result-previous.time)/1000).toFixed(3)} 秒`:'已保存幽灵。'}</p><p>${race.valid?(race.result<=track.medals.gold?'★ 金牌':race.result<=track.medals.silver?'★ 银牌':race.result<=track.medals.bronze?'★ 铜牌':'完赛'):''}</p><details><summary>分段</summary><p>${race.splits.map(formatTime).join(' / ')}</p></details><div class="actions"><button class="primary" id="again">重开 ↗</button><button class="secondary" id="results-board">排行</button><button class="secondary" id="result-home">主页</button></div>`);$('again').onclick=start;$('results-board').onclick=()=>void leaderboard('weekly');$('result-home').onclick=()=>{close();mode='menu';vehicle.reset(track.spawn);renderUI();};
 }
 function control(){return readControl(keys,touch,platform.settings.autoThrottle)}
 function tick(){if(mode!=='race'||modal)return;if(platform.generation!==identityAtStart)race.invalidate('账号已切换 · 请重新开始');const input=control();vehicle.step(input);scene.trails.update(vehicle);if(vehicle.grounded&&lastGround===0)sound.play('impact',.25);if(lastSpeed-vehicle.speed>5)sound.play('impact',.6);lastGround=vehicle.grounded;lastSpeed=vehicle.speed;race.step(vehicle.previous,vehicle.position);if(race.ticks%6===0&&frames.length<12001)frames.push(packFrame(race.elapsed,vehicle.position,vehicle.rotation));if(!Number.isFinite(vehicle.position.length())||vehicle.position.y<-55){practiceReset();}
  if(race.next!==lastCP){lastCP=race.next;sound.play('checkpoint');const pb=platform.best?.splits[race.next-1];split=pb!==undefined?`${race.splits[race.next-1]-pb>0?'+':''}${((race.splits[race.next-1]-pb)/1000).toFixed(3)} s`:'检查点通过';}if(race.finished)finish();
 }
 const xs=track.samples.map(s=>s.p[0]),zs=track.samples.map(s=>s.p[2]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),mapScale=Math.min(300/(maxX-minX),240/(maxZ-minZ));
 function drawMap(){const c=document.querySelector<HTMLCanvasElement>('#minimap');if(!c)return;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,360,300);const xy=(p:number[])=>[30+(p[0]-minX)*mapScale,270-(p[2]-minZ)*mapScale];ctx.lineWidth=4;ctx.strokeStyle='#63dce4aa';ctx.beginPath();track.samples.forEach((s,i)=>{const [x,y]=xy(s.p);if(i===0||!s.road)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();const [x,y]=xy(vehicle.position.toArray());ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();}
 function frame(now:number){const dt=(now-last)/1000;last=now;if(dt>0&&dt<.25){frameTimes.push(dt*1000);if(frameTimes.length>300)frameTimes.shift();}if(diagnostics&&document.getElementById('diagnostics')&&frameTimes.length){const sorted=[...frameTimes].sort((a,b)=>a-b);$('diagnostics').textContent=`${innerWidth} × ${innerHeight} | DPR ${scene.renderer.getPixelRatio()}\nFPS ${(1000/(frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length)).toFixed(1)} | p95 ${sorted[Math.floor(sorted.length*.95)].toFixed(1)} ms\nDraw calls ${scene.renderer.info.render.calls} | Triangles ${scene.renderer.info.render.triangles}\nSamples ${frameTimes.length}`;}if(mode==='race'&&!modal)clock.advance(dt,tick,()=>race.invalidate('运行卡顿 · 练习局'));if(mode==='race'){ $('time').textContent=formatTime(race.elapsed);$('speed').textContent=String(Math.round(Math.abs(vehicle.speed)*3.6));$('checkpoint').textContent=`CP ${Math.min(race.next,6)} / 6`;$('practice').textContent=race.reason;$('split').textContent=split;}
  scene.ghost.visible=mode==='race'&&platform.settings.ghost&&!!platform.best?.frames.length;if(scene.ghost.visible)playback(platform.best!.frames,race.elapsed,scene.ghost.position,scene.ghost.quaternion);scene.render(vehicle,Math.min(dt,.1),mode==='menu',platform.settings.lowMotion,race.next);sound.tick(vehicle.speed,mode==='race'&&!modal,vehicle.drifting||control().handbrake&&vehicle.grounded>0);drawMap();requestAnimationFrame(frame);}
 window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='KeyR'||e.code==='Enter'){e.preventDefault();start();return;}if(e.code==='KeyC'){practiceReset();return;}if(e.code==='Escape'){modal?close():settings();return;}keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();touch.clear();race.invalidate('已离开窗口 · 练习局');});document.addEventListener('visibilitychange',()=>{if(document.hidden){race.invalidate('已切到后台 · 练习局');keys.clear();touch.clear();}});window.addEventListener('resize',()=>scene.resize());
 app.addEventListener('pointerdown',()=>sound.start());app.addEventListener('click',e=>{if((e.target as Element).closest('button'))sound.play('click',.4)});
 renderUI();void platform.init().then(()=>{applySettings();if(mode==='menu')renderUI();});void scene.loadAssets().then(applySettings).catch(e=>{toast='模型加载失败，请刷新重试';console.error(e);});requestAnimationFrame(frame);
}
boot().catch(e=>{app.innerHTML=`<div class="loading"><h1>加载未完成</h1><p></p><button onclick="location.reload()">重新加载</button></div>`;app.querySelector('p')!.textContent=String(e);console.error(e);});

